### ISSUE TITLE
Suggester - Features needed in BO

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues-Back-Office#179]
In order to implement the suggester design in Pogues, several features are needed on the back end side.

> To be completed by @BulotF

**Comment by BulotF** [comment]
pogues-front needs 2 new IPA : 
1) getNomenclatures : list of the nomenclatures and for each : 
   - name / label
   - id
   - version number
   - the suggester parameters needed by Lunatic

2) getNomenclature (needs an id) : 
  - name / label
  - for the list of codes : 
    - code
    - label
    - parent code (optional) : present only for hierarchical codelists

RMéS already provides the second one for non-hierarchical codelists.
It provides the first one without the suggester parameters. A default value is possible.

N.B. Preview the case when DDI Access Service is not present (parameter ?) to plug with default tables in the Pogues database. Preview the same case for series and operations.

**Comment by BulotF** [comment]
endpoints RMéS (à recetter pour vérifier qu'ils répondent bien au besoin) : 
- Liste des codelists dont le nom inclut la chaîne de caractères {texte}
[http://dvrmeswdailm002.ad.insee.intra:8080/Item/filtered-search/{index}/{texte}?index=portal%2A&texte=sugg%2A](http://dvrmeswdailm002.ad.insee.intra:8080/Item/filtered-search/%7Bindex%7D/%7Btexte%7D?index=portal%2A&texte=sugg%2A)
- L'appel à la liste de codes dont l'URL est "d6c08ec1-c4d2-4b9a-b358-b23aa4e0af93"
http://dvrmeswdailm002.ad.insee.intra:8080/Item/suggesters/jsonWithChild?identifier=d6c08ec1-c4d2-4b9a-b358-b23aa4e0af93&fieldIdName=id&fieldLabelName=label

**Comment by laurentC35** [comment]
Synchro with @BulotF and @laurentC35 for API between Pogues-IHM / Pogues-BO

**Comment by romaintailhurat** [comment]
Devs to meet and implement this week

**Comment by nsenave** [comment]
- #220

**Comment by laurentC35** [comment]
Done :
