### ISSUE TITLE
Missing `options` key in composed questionnaire

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues-Back-Office#181]
A question in a composed questionnaire is missing the `options` key (in the generated Lunatic JSON file).

When generating the referenced questionnaire containing this question, the Lunatic JSON file is correct (the `options` key is here and valid).

Hypothesis: the handling of duplicate list code is incorrect, thus producing this bug.

See [previous analysis](https://github.com/InseeFr/Lunatic/issues/646).

**Comment by BulotF** [comment]
The questionnaire is composed with several other questionnaires.

2 of them have codelists with the same name "NeufOccas" and different ids and contents : 
- li4o1otc : 3 values ; in the 4th imported questionnaire ; kept
- lhiw79rq  : 2 values ; in the 5th imported questionnaire : lost

**Comment by laurentC35** [comment]
Check if solution is working with BDF @romaintailhurat

**Comment by romaintailhurat** [comment]
The Lunatic JSON generated by Bowie is now correct, thanks to the renaming of the two code lists.

**Comment by laurentC35** [comment]
Closed, is a bigger issue, linked with https://github.com/InseeFr/Bowie/issues/64
