### ISSUE TITLE
Composition - absence du scope

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Pogues-Back-Office#183]
Evolution à apporter à Pogues-back-office lorsqu’on fait de la composition de questionnaire :

Constat : au niveau du DDI de l’enquête, il y a un conflit entre la déclaration des variables telles qu’elles sont saisies dans le module initial et le référencement de cette variable au niveau du questionnaire de l’enquête. 

Correction à appliquer : 
Si une boucle s’applique au questionnaire, alors :
     -	Pour toute Variable (collectée, externe et calculée) qui n’a pas déjà un Scope (dans le cas où elle en a déjà un, elle le conserve : on est sur une boucle de boucles), on lui affecte un Scope.
      - La valeur de Scope attribuée est : 
          •	l’identifiant de la boucle pour une boucle principale
          •	l’identifiant du basedOn sinon

**Comment by romaintailhurat** [comment]
@laurentC35 need to check who can work on that

**Comment by romaintailhurat** [comment]
> vérifier dans le DDI que les VariableReference des variables collectées sont dans le VariableGroup de la boucle ; actuellement, ils sont dans le VariableGroup de la racine du questionnaire

**Comment by romaintailhurat** [comment]
Some use cases are still to be addressed, and probably in the front says @BulotF

**Comment by romaintailhurat** [comment]
Both cases are validated!

**Comment by nsenave** [comment]
@AnneHuSKa @romaintailhurat Il me semble que le problème est résolu, je close l'issue
