### ISSUE TITLE
The CATI visualisation does not include any sub-questionnaires.

### ISSUE THREAD

**Issue by bwerquin** [InseeFr/Pogues-Back-Office#184]
The back office method does not dereference the questionnaire before Lunatic generation : https://github.com/InseeFr/Pogues-Back-Office/blob/main/src/main/java/fr/insee/pogues/webservice/rest/PoguesTransforms.java#L123. Missing params.put("needDeref", ref) and the call of specific transform method : https://github.com/InseeFr/Pogues-Back-Office/blob/main/src/main/java/fr/insee/pogues/transforms/visualize/PoguesJSONToPoguesJSONDerefImpl.java#L76.

**Comment by romaintailhurat** [comment]
@laurentC35 to be included in the next sprint backlog?

**Comment by laurentC35** [comment]
Done !
