### ISSUE TITLE
visualize links : separate web business/household

### ISSUE THREAD

**Issue by QRuhier** [InseeFr/Pogues-Back-Office#317]
# User Story
Currently there is a endpoint for visualize-stromae-v3, which is configured for doing a household generation.
We would need to be able to chose between : 
- visu v3 for business ('business' context as param for Eno)
- visu v3 for household ('household' context as param for Eno)

## Defintion of Done
- [x] mise à jour du end-point concerné 
- [ ] une couche de test a été ajoutée
- [ ] Le développeur a ajouté de la documentation sur le fonctionnement de la feature 
   - doc javaDoc
   - doc swagger

## Scenarios de test
- depuis le swagger, je renseigne le Pogues-Model au format JSON
- je visualise en mode entreprise avec le nouveau end-point et je le visualise depuis Stromae-DSFR
- je visualise en mode ménage avec le nouveau end-point et je le visualise depuis Stromae-DSFR

see https://github.com/InseeFr/Pogues/issues/798

**Comment by JulienCarmona** [comment]
# Validation QF  ✅ 
Testé à partir de ce questionnaire  [m331cz44-pogues.json](https://github.com/user-attachments/files/17951362/m331cz44-pogues.json)
Et avec PE

App | Versions
-- | --
Eno Java | [3.29.0-hotfix.2](https://github.com/InseeFr/Eno/tree/3.29.0-hotfix.2)
Eno XML | [2.6.0](https://github.com/InseeFr/Eno-WS/tree/2.6.0)
Pogues Back Office | [4.9.2-SNAPSHOT.1](https://github.com/InseeFr/Pogues-Back-Office/tree/4.9.2-SNAPSHOT.1)
stromae-dsf/Lunatic | [1.3.0](https://github.com/InseeFr/stromae-dsfr/tree/v1.3.0) / [3.4.7](https://github.com/InseeFr/Lunatic/tree/3.4.7)

## Résultats 
- DEFAULT = meme visu que la visu depuis Pogues
- BUSINESS = meme visu que depuis PE business
- HOUSEHOLD = meme visu que depuis PE HOUSEHOLD

### :beetle: Autres Bugs détectés ⚠️ 
- Dans le contexte BUSINESS, bug pour le rond-point. @nsenave est ce que c'est normal ? Ca fait du sens que ce ne soit pas supporté car le rond-point n'est destiné que pour les enquêtes ménages

**Comment by nsenave** [comment]
Ready à être déployé en prod dans la release [`4.9.3`](https://github.com/InseeFr/Pogues-Back-Office/releases/tag/4.9.3)

(Par rapport à la 4.9.2 : une montée de version spring pour corriger une CVE, sans impact pour nous, je déploie déjà en recette pour que tu puisses constater que l'appli tourne toujours bien par acquis de conscience)
